set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports Crystal_oscillator] 
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]
set_property IOSTANDARD LVCMOS33 [get_ports x_mealy]
set_property IOSTANDARD LVCMOS33 [get_ports x_moore]
set_property IOSTANDARD LVCMOS33 [get_ports z_mealy]
set_property IOSTANDARD LVCMOS33 [get_ports z_moore]

set_property PACKAGE_PIN R17 [get_ports rst]
set_property PACKAGE_PIN P17 [get_ports Crystal_oscillator]
set_property PACKAGE_PIN R15 [get_ports clk]
set_property PACKAGE_PIN P5 [get_ports x_mealy]
set_property PACKAGE_PIN R1 [get_ports x_moore]
set_property PACKAGE_PIN F6 [get_ports z_mealy]
set_property PACKAGE_PIN K2 [get_ports z_moore]
